services:
  redis:
    image: redis
    environment:
      TZ: America/Sao_Paulo
  mongo:
    image: mongo
    environment:
      TZ: America/Sao_Paulo
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
  app:
    build: .
    ports:
      - 9000:8000
    command:
      - uvicorn
      - python_fastapi_mongo_template:asgi
